# Generated by Django 2.1.5 on 2019-03-18 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteAcceptanceProcedure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waste_acceptance_checklist', models.FileField(upload_to='')),
                ('waste_manifest_doc', models.FileField(upload_to='')),
                ('waste_handover_doc', models.FileField(upload_to='', verbose_name='waste handover/ transfer note')),
                ('waste_inventory_register', models.FileField(upload_to='')),
                ('waste_tracking_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.ServiceInstruction')),
            ],
        ),
    ]
