# Generated by Django 2.1.5 on 2019-03-18 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('waste_treatment', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executive_summary', models.FileField(upload_to=None)),
                ('hse_report', models.FileField(upload_to=None)),
                ('waste_mangement_activity_report', models.FileField(upload_to=None)),
                ('contract_admin_report', models.FileField(upload_to='', verbose_name='Contract Administration and Managment Report')),
                ('quality_report', models.FileField(upload_to='', verbose_name='QA QC Report')),
                ('monthy_plans', models.FileField(upload_to='', verbose_name='Monthly Pland and Objectives Report')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceInstructionReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_off_order', models.FileField(upload_to='')),
                ('service_instruction', models.FileField(upload_to='')),
                ('waste_management_plan', models.FileField(upload_to='')),
                ('waste_disposal_certificate', models.FileField(upload_to='', verbose_name='Waste Disposal Certificate')),
                ('invoice', models.FileField(upload_to='')),
                ('lab_analysis_reports', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waste_treatment.WasteTreatmentProcedure')),
            ],
        ),
    ]
