# Generated by Django 2.1.5 on 2019-03-18 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteManagementProcedure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waste_collection_procedure_doc', models.FileField(upload_to='')),
                ('permit_to_work', models.FileField(upload_to='')),
                ('site_induction_and_orientation', models.FileField(upload_to='')),
                ('job_hazard_analysis', models.FileField(upload_to='')),
                ('tool_box', models.FileField(upload_to='')),
                ('waste_manifest', models.FileField(upload_to='')),
                ('waste_handover_form', models.FileField(upload_to='', verbose_name='Waste Handover/ Transfer Note')),
                ('waste_tracking_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.ServiceInstruction')),
            ],
        ),
    ]
