# Generated by Django 2.1.5 on 2019-03-18 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_order_request', models.FileField(upload_to=None)),
                ('acceptace_certificate', models.FileField(upload_to='')),
                ('change_order_instruction', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Deviation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviation_request', models.FileField(upload_to='')),
                ('acceptance', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_of_storage', models.IntegerField(verbose_name='Days of Storage')),
            ],
        ),
        migrations.CreateModel(
            name='TechnicalQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technical_query', models.FileField(upload_to='')),
                ('response', models.BooleanField()),
                ('notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Vessel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('description_of_vessel', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('truck_license', models.FileField(upload_to='', verbose_name='Truck/ NEMA licence')),
            ],
        ),
        migrations.CreateModel(
            name='WasteFacilitie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('facility_licence', models.FileField(upload_to='')),
                ('location', models.CharField(max_length=20)),
                ('distance_jbr', models.IntegerField(verbose_name='Distance from JBR04')),
                ('distance_ia', models.IntegerField(verbose_name='Distance from Industrial Area')),
                ('waste_criteria', models.FileField(upload_to='', verbose_name='Attach Waste Acceptance Criteria')),
                ('equipment', models.ManyToManyField(to='waste.Equipment')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.Company')),
            ],
        ),
        migrations.CreateModel(
            name='WasteManagementPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reduce', models.BooleanField()),
                ('reuse', models.BooleanField()),
                ('recycle', models.BooleanField()),
                ('recover', models.BooleanField()),
                ('responsible_treatment_and_disposal', models.BooleanField()),
                ('period_of_storage', models.IntegerField(verbose_name='Duration of Storage in Days')),
                ('notes', models.TextField()),
                ('waste_collection_procedure', models.FileField(upload_to='')),
                ('waste_acceptance_procedurie', models.FileField(upload_to='')),
                ('waste_treatment_procedure', models.FileField(upload_to='')),
                ('change_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waste.ChangeOrder')),
                ('deviation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waste.Deviation')),
                ('facility', models.ManyToManyField(to='waste.WasteFacilitie')),
                ('logistics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waste.Vessel')),
                ('service_instruction_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.ServiceInstruction')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waste.Storage')),
            ],
        ),
        migrations.CreateModel(
            name='WasteMangementPlanApproval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField()),
                ('comment', models.TextField()),
                ('approved_by', models.CharField(max_length=30)),
                ('date_of_approval', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waste.WasteManagementPlan')),
            ],
        ),
        migrations.AddField(
            model_name='storage',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waste.WasteFacilitie'),
        ),
    ]
