# Generated by Django 2.1.5 on 2019-03-18 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_results', models.FileField(upload_to='', verbose_name='laboratory results')),
            ],
        ),
        migrations.CreateModel(
            name='LabServiceRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waste_tracking_number', models.CharField(max_length=10)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('parameters', models.CharField(choices=[(1, 'Effluent Dischard'), (2, 'Sanitary Effluent Discharge'), (3, 'Soil Quality'), (4, 'Ionising and Radiation')], default=1, max_length=20)),
                ('order_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.ServiceInstruction')),
                ('waste_description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.WasteTransferOrder')),
            ],
        ),
        migrations.CreateModel(
            name='TransportServiceRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waste', models.CharField(choices=[('HOO1', 'Aggregate Bitumen'), ('H002', 'Chemical Adhesives'), ('HOO3', 'Chemical Cleaning'), ('H004', 'Chemical Paint'), ('H005', 'Chemical Paint Solvents')], default='H003', max_length=20)),
                ('expected_date', models.DateField()),
                ('inspect_waste', models.BooleanField(default=False)),
                ('collect_waste', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(max_length=30)),
                ('registration_number', models.CharField(max_length=10)),
                ('can_handle_toxic_load', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='transportservicerequest',
            name='vehicle_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Vehicle'),
        ),
    ]
