# Generated by Django 2.1.5 on 2019-02-05 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallOffOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction_title', models.CharField(max_length=100)),
                ('contractor_ref', models.CharField(max_length=30, null=True)),
                ('service_description', models.TextField()),
                ('total_value', models.IntegerField()),
                ('company_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.Company')),
                ('representative_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WasteTransferOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waste_description', models.TextField()),
                ('frequency', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('unit_of_measurement', models.CharField(max_length=10)),
                ('total_amount', models.PositiveIntegerField()),
                ('waste_transfer_note_number', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='callofforder',
            name='waste_transfer_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.WasteTransferOrder'),
        ),
    ]
