# Generated by Django 2.1.5 on 2019-03-18 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceInstruction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_instruction_number', models.CharField(max_length=10)),
                ('instruction_title', models.CharField(max_length=100)),
                ('waste_tracking_number', models.CharField(max_length=30, null=True)),
                ('service_description', models.TextField()),
                ('waste_description', models.CharField(choices=[('H', 'Hazadous'), ('NH', 'Non Hazadous')], default='H', max_length=10)),
                ('waste_code', models.CharField(choices=[('HOO1', 'Aggregate Bitumen'), ('H002', 'Chemical Adhesives'), ('HOO3', 'Chemical Cleaning'), ('H004', 'Chemical Paint'), ('H005', 'Chemical Paint Solvents')], default='H001', max_length=10)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_of_measurement', models.CharField(max_length=10)),
                ('waste_profile', models.FileField(upload_to='', verbose_name='waste profile')),
                ('msds', models.FileField(upload_to='', verbose_name='MSDS')),
                ('representative_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('waste_generator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.Company')),
            ],
        ),
        migrations.CreateModel(
            name='WasteTransferOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waste_description', models.TextField()),
                ('frequency', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('unit_of_measurement', models.CharField(max_length=10)),
                ('total_amount', models.PositiveIntegerField()),
            ],
        ),
    ]
