# Generated by Django 2.1.5 on 2019-02-08 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wastetransferorder',
            name='waste_transfer_note_number',
        ),
    ]
